let students = [
    { rollNo: '24B21A42A0', name: 'CHELLUBOYINA NAGA LOKESH', branch: 'CSM', year: '1st year' },
    { rollNo: '24B21A4502', name: 'SASI SPANDANA BALLA', branch: 'AID', year: '1st year' },
    { rollNo: '246Q1A4505', name: 'Jangala Arvind Kumar', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4558', name: 'Choutapalli sumanth nihal', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4538', name: 'Pokuru Ramakrishna chari', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4557', name: 'Cheeday Pujith sai', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4626', name: 'ALLU VENKATA SAI MANIKANTA', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4619', name: 'karry joshi chandra', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4571', name: 'SAHU NARENDRA', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4616', name: 'Kagita Naga venkateswaro', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '246Q1A4605', name: 'Mopada Purna Durga satyam naidu', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4615', name: 'M.balaji sai swaroop', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4601', name: 'K Mrudula', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4536', name: 'Dwarampudi Bhargava Sai Rakesh Reddy', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4230', name: 'Suthapalli Durga Prasad', branch: 'CSM', year: '1st year' },
    { rollNo: '246Q1A4504', name: 'PITCHIKA REVANTH SATYA NAGA SRINIVAS', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4617', name: 'Bitra.Liladhayr', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4504', name: 'GRANDHI.RAMYA', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4539', name: 'Koyilada prem venkata satya Siva naidu', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4631', name: 'P.Ram Charan', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '246Q1A4602', name: 'Gandepalli Maruthi Venkatesh', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4511', name: 'Yasa.Divya naga durga pavani', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4518', name: 'Pathivada Pujitha', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4519', name: 'L.PUSHYA AASHRITHA', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4212', name: 'Samayamanthula Aasritha', branch: 'CSM', year: '1st year' },
    { rollNo: '24B21A4461', name: 'Manipati Sri Anand', branch: 'CSD', year: '1st year' },
    { rollNo: '24B21A4520', name: 'Hasini Addanki', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4329', name: 'Pilli.shanmukha sai venkata raju', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4307', name: 'Anitha Chowdary', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4522', name: 'Hemavathi saidhu', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4655', name: 'NUKALA PAVAN KARTHIK', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4607', name: 'B.Reshma sri', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A4606', name: 'Jyothika', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '24B21A45D5', name: 'yeduru abhiram', branch: 'AID', year: '1st year' },
    { rollNo: '24B21A4481', name: 'Guthula vinay', branch: 'CSD', year: '1st year' },
    { rollNo: '246Q1A4307', name: 'B. Yuvaraj', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4369', name: 'Dasari.asritha', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4370', name: 'MUGADA PAVAN SANTHOSH', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4479', name: 'Indugupalli Dinesh', branch: 'CSD', year: '1st year' },
    { rollNo: '246Q1A4311', name: 'KALLA VEERA VENKATA SATYA SAI', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4396', name: 'Athili Mounika devi', branch: 'CAI', year: '1st year' },
    { rollNo: '246Q1A4210', name: 'BYREDDY GURU VISHNU REDDY', branch: 'CSM', year: '1st year' },
    { rollNo: '24B21A4579', name: 'MUNURU SRAVANI', branch: 'AID', year: '1st year' },
    { rollNo: '246Q1A4316', name: 'Geesala Harshini', branch: 'CAI', year: '1st year' },
    { rollNo: '24B21A4435', name: 'yaswanth jada', branch: 'CSD', year: '1st year' },
    { rollNo: '24B21A4231', name: 'Kavati Eswararao', branch: 'CSM', year: '1st year' },
    { rollNo: '24B21A4389', name: 'MANEPALLI RAMESH', branch: 'CAI', year: '1st year' },
    { rollNo: '23B21A4531', name: 'Pranathi', branch: 'AID', year: '2nd year' },
    { rollNo: '236Q1A4504', name: 'Sanapathi susmitha', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4522', name: 'GADDAM MANASA PRIYA', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4504', name: 'Koyya bhavya akshaya', branch: 'AID', year: '2nd year' },
    { rollNo: '236Q1A4506', name: 'K Surya Praveen', branch: 'AID', year: '2nd year' },
    { rollNo: '237Q1A4505', name: 'Vijjina Rama Krishna', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4553', name: 'SURADA DHANESH', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4518', name: 'v.syamala', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4410', name: 'Vallam Reddy Allabhi Reddy', branch: 'CSD', year: '2nd year' },
    { rollNo: '23B21A4530', name: 'G. DEVI SRI', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4482', name: 'N.Pushpa Latha', branch: 'CSD', year: '2nd year' },
    { rollNo: '236Q1A4503', name: 'DASAMSETTI ABHI CHANDANA', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4412', name: 'K.vyshnavi', branch: 'CSD', year: '2nd year' },
    { rollNo: '23B21A4411', name: 'G.SAI PAVANI', branch: 'CSD', year: '2nd year' },
    { rollNo: '22B21A4276', name: 'TENELA BHAVANI', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A4279', name: 'Poojitha Karanam', branch: 'CSM', year: '3rd year' },
    { rollNo: '226Q1A4516', name: 'P N S S S ANAND', branch: 'AID', year: '3rd year' },
    { rollNo: '226Q1A4519', name: 'Udata Rama Koti Satya Pavan Kumar', branch: 'AID', year: '3rd year' },
    { rollNo: '23B21A4442', name: 'CHODISETTI SIVA NAGA SATYANARAYANA', branch: 'CSD', year: '2nd year' },
    { rollNo: '24B25A4507', name: 'A.Moksha Varshitha', branch: 'AID', year: '1st year' },
    { rollNo: '24B25A4504', name: 'Ayyanki Thanusha', branch: 'AID', year: '1st year' },
    { rollNo: '226Q1A4529', name: 'BalaRaja Chelikani', branch: 'AID', year: '3rd year' },
    { rollNo: '23B21A4413', name: 'T.Rishitha Sree', branch: 'CSD', year: '2nd year' },
    { rollNo: '22B21A4214', name: 'MUMMIDI YUVA VISHNU GOWRINADH', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A4287', name: 'D Vijaya Durga Prasad', branch: 'CSM', year: '3rd year' },
    { rollNo: '226Q1A4559', name: 'Nimmagadda Manikanata', branch: 'AID', year: '3rd year' },
    { rollNo: '226Q1A4510', name: 'Burela sivaramavenkatakrishna', branch: 'AID', year: '3rd year' },
    { rollNo: '24B25A4209', name: 'Y. Jaswanth Sai varma', branch: 'CSM', year: '1st year' },
    { rollNo: '22B21A4409', name: 'RAJANA SWATHI', branch: 'CSD', year: '3rd year' },
    { rollNo: '22B21A4335', name: 'MAGI SRI RAMA SATYA GANESH', branch: 'CAI', year: '3rd year' },
    { rollNo: '22B21A4355', name: 'P siva sai hanuaman', branch: 'CAI', year: '3rd year' },
    { rollNo: '22B21A4293', name: 'Ch.devi Vara Prasad', branch: 'CSM', year: '3rd year' },
    { rollNo: '226Q1A4410', name: 'Nittala Sai Vara Prasad Gupta', branch: 'CSD', year: '3rd year' },
    { rollNo: '24B25A4214', name: 'DARLA SATYANARAYANA', branch: 'CSM', year: '1st year' },
    { rollNo: '22B21A4320', name: 'A.mounika', branch: 'CAI', year: '3rd year' },
    { rollNo: '246Q5A4201', name: 'Vadlamuri Pardhiv', branch: 'CSM', year: '1st year' },
    { rollNo: '24B25A4210', name: 'K.Venkat Sai Tejesh', branch: 'CSM', year: '1st year' },
    { rollNo: '23B25A4211', name: 'NANDIKOLLA SATYA SURYA KIRAN', branch: 'CSM', year: '2nd year' },
    { rollNo: '22B21A4231', name: 'POLISETTI CHIRANJEEVI NAGA VENKATA SIVA SRAVAN KUMAR', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A4221', name: 'PENDYALA SATISH', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A4220', name: 'Madimetla Yashodhar', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A4312', name: 'YARRAM TEJASWINI', branch: 'CAI', year: '3rd year' },
    { rollNo: '22B21A4245', name: 'Dosakayalapati Tarun', branch: 'CSM', year: '3rd year' },
    { rollNo: '226Q1A4301', name: 'Roselin Katuri', branch: 'CAI', year: '3rd year' },
    { rollNo: '22B21A4575', name: 'Kanda Durga Veera Sai', branch: 'AID', year: '3rd year' },
    { rollNo: '22B21A4592', name: 'Pepakayala Meghana Ratna Maruthi', branch: 'AID', year: '3rd year' },
    { rollNo: '24B21A4673', name: 'Surampudimounika', branch: 'Cyber Security', year: '1st year' },
    { rollNo: '22B21A4246', name: 'KANDA NAGA DATTA', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A44D5', name: 'N kanaka Rathna chari', branch: 'CSD', year: '3rd year' },
    { rollNo: '22B21A42B8', name: 'REDDY NAGENDRA SWAMY', branch: 'CSM', year: '3rd year' },
    { rollNo: '22B21A4227', name: 'Madavarapu Sai Harshavardhan', branch: 'CSM', year: '3rd year' },
    { rollNo: '23B21A4538', name: 'PECHETTI SRIRAMA CHANDRA MURTHI', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4537', name: 'KOMMULA VENKATA SAI JAGADEESH', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4533', name: 'K. Lokesh', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4535', name: 'GUBBALA KUMAR PAVAN MANIKANTHA', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4554', name: 'Pechetti Lakshman kumar', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4502', name: 'GUBBALA RAMYA SRI LAKSHMI', branch: 'AID', year: '2nd year' },
    { rollNo: '23B21A4503', name: 'NANGI LALITHA', branch: 'AID', year: '2nd year' },
    { rollNo: '226Q1A4602', name: 'Pooja Gogineni', branch: 'Cyber Security', year: '3rd year' },
    { rollNo: '23B21A4322', name: 'GEESALA VEERA VENKATA GANAPATHI', branch: 'CAI', year: '2nd year' },
    { rollNo: '22B21A4309', name: 'SAKA.GLORIA', branch: 'CAI', year: '3rd year' },
    { rollNo: '22B21A4582', name: 'JALADURGA AKKISHETTI', branch: 'AID', year: '3rd year' },
    { rollNo: '226Q1A4528', name: 'Hima bindu Ramadevu', branch: 'AID', year: '3rd year' },
    { rollNo: '23B21A45D6', name: 'ANDHE AAKASH', branch: 'AID', year: '2nd year' },
    { rollNo: '22B21A4589', name: 'POOJA VISWANADUNI', branch: 'AID', year: '3rd year' },
    { rollNo: '22B21A4587', name: 'B.Umadevi', branch: 'AID', year: '3rd year' },
    { rollNo: '22B21A4586', name: 'G Mary prameela', branch: 'AID', year: '3rd year' },
    { rollNo: '23B21A4560', name: 'GUTTULA MOHAN DURGA', branch: 'AID', year: '2nd year' }
];